[package]
name = "satellites-service"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2018"

[dependencies]
async-graphql = "2.4.11"
async-graphql-actix-web = "2.4.11"
actix-web = "3.3.2"
actix-rt = "1.1.1"
serde = { version = "1.0.119", features = ["derive"] }
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
strum = "0.20.0"
strum_macros = "0.20.1"

[dev-dependencies]
serde_json = "1.0.61"
jsonpath_lib = "0.2.6"
testcontainers = "0.9.1"
