[package]
name = "auth-service"
version = "0.1.0"
authors = ["Roman Kudryashov <rskudryashov@gmail.com>"]
edition = "2021"

[dependencies]
common-utils = { path = "../common-utils" }
async-graphql = "4.0.13"
async-graphql-actix-web = "4.0.13"
actix-web = "4.2.1"
actix-rt = "2.7.0"
serde = { version = "1.0.144", features = ["derive"] }
diesel = { version = "2.0.0", features = ["postgres", "r2d2"] }
diesel_migrations = "2.0.0"
dotenv = "0.15.0"
jsonwebtoken = "8.1.1"
argonautica = "0.2.0"
chrono = "0.4.22"
lazy_static = "1.4.0"
strum = "0.24.1"
strum_macros = "0.24.3"

[dev-dependencies]
serde_json = "1.0.85"
jsonpath_lib = "0.3.0"
base64 = "0.13.0"
testcontainers = "0.14.0"
